import requests
url = "https://ssd.jpl.nasa.gov/api/horizons.api"
url += "?MAKE_EPHEM=YES"
url += "&COMMAND='DES%3D2000001%3B'"
url += "&EPHEM_TYPE=OBSERVER"
url += "&CENTER='coord@399'"
url += "&COORD_TYPE=GEODETIC"
url += "&SITE_COORD='8.60986388888,47.70550277777,0.54'"
url += "&START_TIME='2022-02-10'"
url += "&STOP_TIME='2022-02-11'"
url += "&STEP_SIZE='1 HOURS'"
url += "&QUANTITIES='1'"
url += "&REF_SYSTEM=ICRF"
url += "&CAL_FORMAT=BOTH"
url += "&TIME_DIGITS=MINUTES"
url += "&ANG_FORMAT=DEG"
url += "&APPARENT=AIRLESS"
url += "&RANGE_UNITS=AU"
url += "&SUPPRESS_RANGE_RATE=NO"
url += "&ELEV_CUT='0'"
url += "&SKIP_DAYLT=NO"
url += "&SOLAR_ELONG='0,180'"
url += "&EXTRA_PREC=NO"
url += "&R_T_S_ONLY=NO"
url += "&CSV_FORMAT=YES"
url += "&OBJ_DATA=NO"
response = requests.get(url)
print (response.text)
